name: Devbox Update

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pull-requests: write

jobs:
  update-devbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Update Devbox
        run: devbox update

      - name: Check for changes
        id: git-check
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create PR
        if: steps.git-check.outputs.changes == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Setup git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create branch and commit
          git checkout -b automated/devbox-update
          git add devbox.lock
          git commit -m "chore(deps): update devbox.lock"
          git push -f origin automated/devbox-update

          # Check if PR exists and create or update accordingly
          if ! gh pr view automated/devbox-update &>/dev/null; then
            gh pr create \
              --title "chore(deps): update devbox dependencies" \
              --body "This PR updates devbox dependencies to their latest versions.

              This is an automated PR created by the devbox-update workflow." \
              --base master \
              --head automated/devbox-update
          fi
