sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - docker build -t alakae/trackz -f ./web/Dockerfile.dev ./web
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker run alakae/trackz npm help

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master