sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - docker build -t alakae/trackz -f ./web/Dockerfile.dev ./web
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker run --env CI=true alakae/trackz npm run test

before_deploy:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin
  - openssl aes-256-cbc -K $encrypted_d0f036b99c7e_key -iv $encrypted_d0f036b99c7e_iv -in config.enc -out config -d
  - mkdir ~/.kube
  - mv config ~/.kube

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master