apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: trackz
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: trackz.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: web-cluster-ip-service
              servicePort: 6601
    - host: www.trackz.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: web-cluster-ip-service
              servicePort: 6601
    - host: matomo.trackz.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: matomo-app-cluster-ip-service
              servicePort: 8888
