apiVersion: v1
kind: Service
metadata:
  name: matomo-app-cluster-ip-service
  namespace: trackz
spec:
  type: ClusterIP
  selector:
    component: matomo-app
  ports:
    - port: 8888
      targetPort: 80