apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-db-persistent-volume-claim
  namespace: trackz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: cloudscale-volume-ssd